services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/entrypoint.sh"]
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 4G
    restart: unless-stopped

  fastapi_proxy:
    build: .
    container_name: fastapi-proxy
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama-server:11434
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 32M
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
