services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    restart: unless-stopped

  fastapi_proxy:
    build: .
    container_name: fastapi-proxy
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama-server:11434
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
