#!/bin/sh
set -e

export OLLAMA_NUM_PARALLEL=2
export OLLAMA_NUM_THREADS=2
export OLLAMA_MAX_LOADED_MODELS=1
export OLLAMA_KEEP_ALIVE=-1
export OLLAMA_FLASH_ATTENTION=1
export OLLAMA_NUM_GPU=1
export OLLAMA_HOST="0.0.0.0:11434"

exec ollama serve
